nytimes/NYTPhotoViewer

- README.md
For developers new to Swift and/or CocoaPods, I think it would be helpful to have a reminder that they'll need an Objective-C bridging header to use NYTPhotoViewer in their Swift project. My addition includes links to Apple's explanation and to the example Swift app's bridging header for reference.
> Adds Objective-C bridging header info to README

- Example/Tests/NYTPhotosViewControllerTests.m
- Pod/Classes/ios/NYTPhotosOverlayView.h
- Pod/Classes/ios/NYTPhotosOverlayView.m
- Pod/Classes/ios/NYTPhotosViewController.h
- Pod/Classes/ios/NYTPhotosViewController.m
Adds support for setting `rightBarButtonItems` and `leftBarButtonItems` on `NYTPhotosViewController`.
> Allow setting multiple bar button items for a side

- Pod/Classes/ios/NYTPhotosOverlayView.m
This is a simple addition to the “Make navigation bar fully transparent” logic already present in `NYTPhotosOverlayView`.
This addresses the navigation bar coloring issue revealed in https://github.com/NYTimes/NYTPhotoViewer/issues/55 , while still allowing users to customize the bar’s tint color and title text attributes via `UIAppearance`.
closes #55
> Ensure nav bar is translucent and has no tint color

- README.md
Removes the TODO mentioning Swift sample project from README since this is now in the main branch.
Read over the README, I guess.
> Remove TODO for Swift sample project from README

- Example/NYTPhotoViewer-SwiftTests/NYTPhotosOverlayViewTests.swift
per feedback on https://github.com/NYTimes/NYTPhotoViewer/pull/76
> Use optional instead of forced unwrapping in Swift unit tests

- Pod/Classes/ios/NYTPhotoDismissalInteractionController.m
NYTPhotosViewController leaks memory by circular reference around interactive transition.
NYTPhotosViewController is not released when you attempt to dismiss interactively.
That occurs even when transition is canceled. Therefore it leaks by swipe-up/down the picture just once.
(-[NYTPhotosViewController dealloc] is never called.)
A concrete class of UIViewControllerContextTransitioning has got view controllers internally as strong reference.
Circular reference appears to be happening as follows:
- NYTPhotosViewController has got NYTPhotoTransitionController
- NYTPhotoTransitionController has got NYTPhotoDismissalInteractionController
- NYTPhotoDismissalInteractionController has got UIViewControllerContextTransitioning
- **UIViewControllerContextTransitioning has got …
> Fix circular reference of NYTPhotosViewController

- Pod/Classes/ios/NYTPhotosOverlayView.h
- Pod/Classes/ios/NYTPhotosViewController.h
- Pod/Classes/ios/Protocols/NYTPhoto.h
For expediency in this PR, I focused on the classes identified as significant public API in the Carthage support PR: https://github.com/NYTimes/NYTPhotoViewer/pull/63#issuecomment-123029687
> Nullability and lightweight generics annotations on important public API

- Pod/Classes/ios/NYTPhotosViewController.m
Update overlay information after displaying a photo to reflect its actual position in the array.
Addresses Issue #99.
> update overlay information after displaying a photo

- Pod/Classes/ios/NYTPhotoTransitionAnimator.m
Removes a method, which is now unused, that was created to workaround a bug on iOS 7 that is no longer relevant since the minimum version for this project is now iOS 8.
> Removes Unused iOS 7 Workaround Method

- Pod/Classes/ios/NYTPhotoDismissalInteractionController.m
- Pod/Classes/ios/NYTPhotoTransitionAnimator.m
Switches the animated and interactive transition from using `hidden` to `alpha`.
Using `hidden` to control the visibility of `UIView`’s contained in [`UIStackView`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIStackView_Class_Reference/) has the side effect of affecting the layout of items within the stack view. Setting the view’s `alpha` does not have this
effect.
1. Embed the Image Button in the sample project inside a `UIStackView` including other views.
2. Tap on the Image Button and confirm that the animated presentation and dismissal go to and from the correct frame.
cc @bcapps who co-authored this patch.
> Fixes a bug when presenting NYTPhotoViewer from a subview of UIStackView

- Example/NYTPhotoViewer.xcodeproj/project.pbxproj
- Example/Tests/NYTScalingImageViewTests.m
- Pod/Classes/ios/NYTPhotoViewController.m
- Pod/Classes/ios/NYTScalingImageView.h
- Pod/Classes/ios/NYTScalingImageView.m
This pull request is a proposal to improve the public API of `NYTScalingImageView` and the internal code of both that class and `NYTPhotoViewer` to elevate using normal `UIImage`s to a first-class behavior after the addition of animated GIF support.
Currently, on develop, `NYTScalingImageView` only has APIs that support `NSData`, which means that `NYTPhoto` objects that only contain a non-animated `UIImage` are shoehorned into an API that then causes `UIImages` to be converted to data (a potentially metadata-lossy conversion) in order to call these APIs, and then _back_ to `UIImage` objects internally in those methods. This is both less performant and more complex than an API that treats `UIImage` and `NSData` equally, as they are in the `NYTPhoto` protocol. This pull request adds that …
> Better UIImage Support

- NYTPhotoViewer.podspec
The podspec _should_ have included a specific version for FLAnimatedImage. This change specifies that `~> 1.0.8` should be used, since that's the version [currently installed in the Example project](https://github.com/NYTimes/NYTPhotoViewer/blob/develop/Example/Podfile.lock#L2).
> Include FLAnimatedImage version in Podspec

- Example/Podfile.lock
- Example/Pods/Local Podspecs/NYTPhotoViewer.podspec.json
- Example/Pods/Manifest.lock
- Example/Pods/Pods.xcodeproj/project.pbxproj
- Example/Pods/Pods.xcodeproj/xcshareddata/xcschemes/NYTPhotoViewer.xcscheme
- Example/Pods/Target Support Files/Pods-NYTPhotoViewer-Swift/Pods-NYTPhotoViewer-Swift-resources.sh
- Example/Pods/Target Support Files/Pods-NYTPhotoViewer-SwiftTests/Pods-NYTPhotoViewer-SwiftTests-resources.sh
- Example/Pods/Target Support Files/Pods-NYTPhotoViewer/Pods-NYTPhotoViewer-resources.sh
- Example/Pods/Target Support Files/Pods-Tests/Pods-Tests-resources.sh
- NYTPhotoViewer.podspec
By moving the resource bundle inside the core subspec, it appears to fix the issue of the close button not appearing appropriately.
Fixes #102
> Fixes Close Button

- Pod/Classes/ios/NYTPhotoTransitionController.m
- Pod/Classes/ios/NYTPhotosViewController.m
Hey!
It seems that default dismissViewControllerAnimated:completion: does not work, because it's interactive.
Correct way to handle this is to make transition interactive only when user starts panning, and disable interactivity by default.
I believe this PR closes #109 as well as #72 and #96. It also allows to call correct delegate callbacks and notifications when dismissing controller.
What do you guys think, am I missing something? 
/cc @cdzombak
> [Feature] Support native dismissViewControllerAnimated:completion: method instead of custom one.

- Pod/Classes/ios/Resource Loading/NSBundle+NYTPhotoViewer.m
(Recreated #114 in a fresh PR) 
In a final attempt to continue using bundles through cocoapods, hopefully this will fix any outstanding issues people are having with getting the close button image.
(Hopefully) Fixes #102
> Use bundleForClass on a NYTPhotoViewer class to retrieve the appropriate bundle

- Pod/Classes/ios/NYTPhotosViewController.m
I've done some minor cleanup and fixed a few minor bugs from the (merged) dismissal fix in #121:
- The completion block supplied to `dismissViewControllerAnimated:…` is no longer ignored: https://github.com/NYTimes/NYTPhotoViewer/commit/79d35948aa950556b01e2a5d830521e884be5113
- Overlay view management on dismissal is now handled in one place for all styles of dismissal: https://github.com/NYTimes/NYTPhotoViewer/commit/c17b7f7e27f231ca4187dba77f3a831f082faa5e
- In keeping with Cocoa convention, delegate methods aren't called for programmatic dismissals: https://github.com/NYTimes/NYTPhotoViewer/commit/e5b3144dd869c61aa7a977587a6d69eb21de8546
- Plus minor naming & code style fixes.
> Followup from dismissal PR #121

- Pod/Classes/ios/NYTPhotosViewController.m
closes #129
This was a stupid reversed-logic bug. I even tried extracting this to a boolean to keep the logic straight, but something with the "forces non interactive" naming messed with my head, I guess.
> Fix delegate calls on interactive dismissal transitions

- Pod/Classes/ios/NYTPhotoTransitionAnimator.m
The issue occurred during in and out animations when the reference
view is a UIImageView containing a UIImage with meaningful
orientation informations (e.g. taken directly with the device in
portrait orientation). See #115.
> Fix orientation issue with reference view of type UIImageView

- Pod/Classes/ios/NYTPhotoViewController.m
> Avoid testing floats for equality in PhotoViewController

- Example/Podfile
- Example/Tests/NYTPhotosOverlayViewTests.m
- Example/Tests/NYTPhotosViewControllerTests.m
- Pod/Classes/ios/NYTPhotosViewController.h
- Pod/Classes/ios/NYTPhotosViewController.m
- Refactor how dismissals are managed, to allow disambiguating user-initiated and programmatic dismissals for determination of whether to send delegate messages, without tracking an additional bit of state.
- https://github.com/NYTimes/NYTPhotoViewer/commit/16bd3c040b69bd5b2b125d1b8f15d1bb03e272ba should've been covered in #128 , but I just now noticed it
- Other commits in this PR are documentation improvements around this behavior, and minor style improvements.
Closes #134.
> Send delegate messages for all user-initiated dismissals

- Pod/Classes/ios/NYTPhotosViewController.h
- Pod/Classes/ios/NYTPhotosViewController.m
Adds a delegate method for customizing the title.
> delegate method to customize title text

- Example/NYTPhotoViewer/NYTViewController.m
- Pod/Classes/ios/NYTPhotosViewController.h
- Pod/Classes/ios/NYTPhotosViewController.m
As a followup from #142, this PR proposes a small API change and further documentation to clarify how our team believes this new avenue for customization should be used.
I've also slightly simplified some of the logic behind it and provided an example implementation in the Example app.
> Clarify how title-text delegate method is intended to be used

- Pod/Classes/ios/NYTPhotosViewController.h
thanks @loganmoseley for pointing these out.
This is followup from #151.
> Fix typos in NYTPhotosViewController header documentation

- Pod/Classes/ios/NYTPhotosViewController.m
- Pod/Classes/ios/NYTScalingImageView.m
- Pod/Classes/ios/Protocols/NYTPhoto.h
This is mostly followup from the changes in #106.
- https://github.com/NYTimes/NYTPhotoViewer/commit/8ece787e3b0f26c70ee8ab5208d8f846f0cb0b6b cleans up one place where we could've seen inconsistent behavior in builds without animated GIF support (see commit message for details)
- https://github.com/NYTimes/NYTPhotoViewer/commit/043299bbb94dbb3340c5ea13ced805b5875d220d is a documentation improvement in `NYTPhoto` about `image` vs `imageData`
- https://github.com/NYTimes/NYTPhotoViewer/commit/34f45a198f4b8b3d4952798f65c71c4056f941a5 adds a warning log message (in debug builds only) when you use the `imageData` property but animated GIF support is compiled out (since that really makes no sense, as discussed in #106)
> Documentation and clarification around NYTPhoto.image vs .imageData

- Example/Tests/NYTPhotosViewControllerTests.m
- Pod/Classes/ios/NYTPhotosViewController.h
- Pod/Classes/ios/NYTPhotosViewController.m
closes #95.
The previous designated initializer remains as a convenience initializer, making this API change non-breaking, and allowing this to be released as a new minor version.
> Add `delegate` to the designated initializer

- NYTPhotoViewer/NYTPhotoCaptionView.m
This implements @cxa's fix from https://github.com/NYTimes/NYTPhotoViewer/pull/165 on top of the large project restructuring from https://github.com/NYTimes/NYTPhotoViewer/pull/164 .
I've reproduced the issue and verfied this fix on an iOS 9 device.
> Fix gradient flickering of caption view on iOS 9

- NYTPhotoViewerTests/NYTScalingImageViewTests.m
When we added Carthage support ( https://github.com/NYTimes/NYTPhotoViewer/pull/164 ), we created two NYTPhotoViewer targets: the “normal” one which includes animated gif support (via `ANIMATED_GIF_SUPPORT=1`, and requires linking with FLAnimatedImage); and the “-Core” target which does not include animated GIF support.
_For brevity I will refer to the library target with animated gif support as “-Normal” even though it doesn’t have that suffix (the “-Core” target _does_ have that suffix)._
The unit tests are configured to run against the “-Normal” target, but they weren’t compiled with `ANIMATED_GIF_SUPPORT=1`, so we were running unit tests intended for “-Core” against the “-Normal” target. This resulted in some test failures.
I’ve fixed them by removing the `ANIMATED_GIF_SUPPORT` …
> Remove `ANIMATED_GIF_SUPPORT` preprocessor conditionals from unit tests

- NYTPhotoViewer.podspec
This change has no functional effect at this time. However, now that we have a proper bundle in the repo, it seems proper to direct CocoaPods to package _all_ files in that bundle into its (equivalent) resource bundle.
This eliminates room for future error: if a non-PNG file is added to the bundle, before this change, it would appear to work with Carthage but not with CocoaPods.
> Include all files in the bundle, not just PNGs, in Cocoapods resource bundle

- NYTPhotoViewer/NYTPhotoViewController.m
This commit prevents the destruction of loading view and adds it back as a subview when the image and imageData is empty.
Fixes issue #186.
> Readd loading view when photo source is set back to nil.

- NYTPhotoViewer.podspec
- NYTPhotoViewer/Info.plist
Cutting a new release will at least bring Carthage support to users on `master`.
> Bump to version 1.2.0

- CHANGELOG.md
- NYTPhotoViewer/NYTPhotosViewController.h
- NYTPhotoViewer/NYTPhotosViewController.m
This fixes two bugs I found while rewriting the Swift example (#223):
* The `PhotosViewController` should not retain its data source. This will lead trivially easily to retain cycles which would be difficult to manage.
* The `PhotosViewController` was asking its data source for nonsensical bounds when scrolling from the first photo. I've added a check to avoid that, and while I was there I added a check to prevent the viewer from skipping back to the first photo when the data source returns `NSNotFound` for a photo.
> Bugfixes: bounds checks, don't retain data source

- README.md
When we switched over to Carthage, we neglected to document the steps needed to get the Example up and running. I've added a section on that subject to the README.
> Add README documentation on Example project dependency management

- CHANGELOG.md
- NYTPhotoViewer/NYTPhotoViewController.m
- NYTPhotoViewer/NYTPhotosOverlayView.h
- NYTPhotoViewer/NYTPhotosOverlayView.m
- NYTPhotoViewer/NYTPhotosViewController.h
- NYTPhotoViewer/NYTPhotosViewController.m
Respects the safe area layout guide for the caption view and the top items (https://github.com/NYTimes/NYTPhotoViewer/issues/246).
Thanks so much to @matthiaskmt for submitting this PR: https://github.com/NYTimes/NYTPhotoViewer/pull/247. We decided to go a slightly different route by adding a delegate method `photosViewController:captionViewRespectsSafeAreaForPhoto:` to allow the client to choose if they want their caption view to adhere to the safe area insets. If a caption has a background view the client may want those colors/gradients/etc. to extend to the edges of the screen.
> Respect Safe Area Layout Guide

- NYTPhotoViewer/NYTPhotoTransitionAnimator.m
When presenting/dismissing `NYTPhotosViewController` the actual presenter's `viewWillAppear`, `viewDidAppear`, `viewWillDisappear` and `viewDidDisappear` methods aren't getting called. This sucks a bit.
The bug is due to the transition animator `NYTPhotoTransitionAnimator` not dispatching `beginAppearanceTransition` and `endAppearanceTransition` calls to the respective ViewControllers.
This PR fixes this.
More background info: http://stackoverflow.com/a/29041911
> Fix: Parent's `viewWillAppear` etc. methods are not getting called

- CHANGELOG.md
- NYTPhotoViewer.xcodeproj/project.pbxproj
- NYTPhotoViewer/NYTPhotosViewController.m
- README.md
- Update the deployment target which should make publishing the podspec work again.
- Removes a `UIPopoverViewController` property. 
[JIRA](https://jira.nyt.net/browse/APP-2020)
> [APP-2020] Up deployment target to 9.0

- NYTPhotoViewer.podspec
> fix: podspec should use 9.0

- .gitmodules
- CHANGELOG.md
When I run `carthage update NYTPhotoViewer`, I get the following error:  
```
Parse error: expected submodule commit SHA in output of task (ls-tree -z 4.0.0 Carthage/Checkouts/FLAnimatedImage) but encountered: 
```
Since FLAnimatedImage has been replaced, Removed from .gitmodule.
> Fix gitmodule

- CHANGELOG.md
- NYTPhotoViewer/NYTPhotoDismissalInteractionController.m
- NYTPhotoViewer/NYTPhotosViewController.m
Change `NYTPhotosViewController` to use fullscreen presentation by default, so it causes the presenting view to disappear behind it, i.e. to get `-viewWillDisappear:` and `-viewDidDisappear:` called on it.
Once this change was made, I noticed that the interactive dismissal transition no longer worked, because the presenting VC's view wasn't put back in the view hierarchy until the end of the transition. So, most of this PR consists of adding the presenting VC's view back at the start of the interactive dismissal, and removing it again if the interactive dismissal is canceled.
**Before:** when the photos VC is fullscreen, the presenting view controller is still in the view hierarchy:
**After:** the presenting VC is no longer in the view hierarchy, even after an interactive dismissal is …
> Capture fullscreen presentation context

- CHANGELOG.md
- NYTPhotoViewer/NYTPhotoTransitionAnimator.m
This addresses an issue in the Example app where presenting `NYTPhotosViewController` logs the following warning:
```
Unbalanced calls to begin/end appearance transitions for <NYTPhotosViewController>.
Unbalanced calls to begin/end appearance transitions for <NYTViewController>.
```
> Fix unbalanced appearance transitions calls

- CHANGELOG.md
- NYTPhotoViewer/NYTPhotoViewerSinglePhotoDataSource.h
- NYTPhotoViewer/NYTPhotosViewController.h
Non functional change. Modified comment parameter in 'NYTPhotosViewController' and 'NYTPhotoViewerSinglePhotoDataSource' to match parameter in signature. Removes compilation warning.
> Modify comment parameters

- NYTPhotoViewer.podspec
Be more explicit about the various subspecs that are needed from PINRemoteImage. This is being done to match [Texture 3.0's podspec](https://github.com/TextureGroup/Texture/blob/9ef97f49657e6e690bb222ef4634bbdcc453c3c2/Texture.podspec#L41) and help address transitive dependency warnings when using Texture 3.0.
> Modify PINRemoteImage dependency

- Cartfile.resolved
Fixes https://github.com/nytimes/NYTPhotoViewer/issues/321
> Bumps PINCache to latest 3.0.1

- .gitignore
- NYTPhotoViewer/NYTPhotoViewController.m
- NYTPhotoViewer/NYTPhotosViewController.m
- NYTPhotoViewer/NYTScalingImageView.m
- Package.resolved
- Package.swift
- SourceSymLink
(avoiding the '[target 2] has source overlapping sources' problem with a symlink)
```swift
targets: [
.target(
name: "NYTPhotoViewer",
path: "NYTPhotoViewer"
),
.target(
name: "NYTPhotoViewerGIF",
dependencies: ["PINRemoteImage"],
path: "SourceSymLink",
cSettings: [
.define("ANIMATED_GIF_SUPPORT", to: "1")
]
)
]
```
```objc
#import <PINRemoteImage/FOO.h>
```
to
```objc
#if SWIFT_PACKAGE
#import "FOO.h"
#else
#import <PINRemoteImage/FOO.h>
#endif
```
> Fix #341 - restore support for animated gifs

- CHANGELOG.md
- NYTPhotoViewer/NYTPhotoCaptionView.m
- NYTPhotoViewer/NYTPhotosViewController.m
Bugfixes to use package in NYT Cooking
- fixed caption overlay placement
- fixed overlay view buttons tint color
- added summary to share
Attached screenshots of current issues:
|Bug_1|Bug_2|Bug_3|
|---|---|---|
|![1](https://user-images.githubusercontent.com/106048886/196735262-789b78f6-81d2-439b-b70f-67d59ccf8d0d.PNG)|![2](https://user-images.githubusercontent.com/106048886/196735261-c9f497b6-c203-45bb-a143-2e072fb65865.PNG)|![3](https://user-images.githubusercontent.com/106048886/196735258-1f566bbf-8cdc-4fa4-ada0-6120703e87d2.jpeg)
> Bugfixes to use package in cooking
